apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/ecs.services.k8s.aws_clusters.yaml
  - bases/ecs.services.k8s.aws_services.yaml
  - bases/ecs.services.k8s.aws_taskdefinitions.yaml
