apiVersion: v1
name: ecs-chart
description: A Helm chart for the ACK service controller for Amazon Elastic Container Service (ECS)
version: 1.0.5
appVersion: 1.0.5
home: https://github.com/aws-controllers-k8s/ecs-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/ecs-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ECS Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ecs-maintainer
keywords:
  - aws
  - kubernetes
  - ecs
